const teamFlags: Record<string, string> = {
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  England: "🏴",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  Italy: "🇮🇹",
  Japan: "🇯🇵",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  Nigeria: "🇳🇬",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  Spain: "🇪🇸",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Switzerland: "🇨🇭",
  Uruguay: "🇺🇾",
  "United States": "🇺🇸",
  USA: "🇺🇸",
};

export function flagForTeam(team: string) {
  return teamFlags[team] || "🏳️";
}
