const teamFlags: Record<string, string> = {
  Argentina: "🇦🇷",
  Algeria: "🇩🇿",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  "Bosnia and Herzegovina": "🇧🇦",
  Brazil: "🇧🇷",
  "Cabo Verde": "🇨🇻",
  "Cape Verde": "🇨🇻",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  "Congo DR": "🇨🇩",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  Curacao: "🇨🇼",
  Curaçao: "🇨🇼",
  Czechia: "🇨🇿",
  Denmark: "🇩🇰",
  "DR Congo": "🇨🇩",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  England: "🏴",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Haiti: "🇭🇹",
  Iran: "🇮🇷",
  "IR Iran": "🇮🇷",
  Iraq: "🇮🇶",
  Italy: "🇮🇹",
  "Ivory Coast": "🇨🇮",
  Japan: "🇯🇵",
  Jordan: "🇯🇴",
  "Korea Republic": "🇰🇷",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Nigeria: "🇳🇬",
  Norway: "🇳🇴",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  Scotland: "🏴",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  Spain: "🇪🇸",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Tunisia: "🇹🇳",
  Turkey: "🇹🇷",
  Türkiye: "🇹🇷",
  Uruguay: "🇺🇾",
  Uzbekistan: "🇺🇿",
  "United States": "🇺🇸",
  USA: "🇺🇸",
};

function normalizeTeamName(value: string) {
  return value
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, " ");
}

const teamFlagAliases: Record<string, string> = {
  alemania: "Germany",
  algeria: "Algeria",
  arg: "Argentina",
  argelia: "Algeria",
  argentina: "Argentina",
  arabia: "Saudi Arabia",
  "arabia saudita": "Saudi Arabia",
  aus: "Australia",
  australia: "Australia",
  austria: "Austria",
  aut: "Austria",
  bel: "Belgium",
  belgica: "Belgium",
  belgium: "Belgium",
  bih: "Bosnia and Herzegovina",
  bosnia: "Bosnia and Herzegovina",
  "bosnia and herzegovina": "Bosnia and Herzegovina",
  bra: "Brazil",
  brasil: "Brazil",
  brazil: "Brazil",
  cabo: "Cape Verde",
  "cabo verde": "Cape Verde",
  can: "Canada",
  canada: "Canada",
  catar: "Qatar",
  "cape verde": "Cape Verde",
  chequia: "Czechia",
  civ: "Ivory Coast",
  cod: "DR Congo",
  col: "Colombia",
  colombia: "Colombia",
  "congo dr": "DR Congo",
  "corea del sur": "South Korea",
  "costa de marfil": "Ivory Coast",
  cro: "Croatia",
  croacia: "Croatia",
  croatia: "Croatia",
  cpv: "Cape Verde",
  curacao: "Curacao",
  curazao: "Curacao",
  cuw: "Curacao",
  cze: "Czechia",
  czechia: "Czechia",
  "czech republic": "Czechia",
  dza: "Algeria",
  "dr congo": "DR Congo",
  ecu: "Ecuador",
  ecuador: "Ecuador",
  egypt: "Egypt",
  egipto: "Egypt",
  egy: "Egypt",
  eng: "England",
  england: "England",
  escocia: "Scotland",
  "estados unidos": "United States",
  esp: "Spain",
  espana: "Spain",
  fra: "France",
  francia: "France",
  france: "France",
  ger: "Germany",
  germany: "Germany",
  gha: "Ghana",
  ghana: "Ghana",
  haiti: "Haiti",
  hti: "Haiti",
  holanda: "Netherlands",
  inglaterra: "England",
  iran: "Iran",
  iri: "IR Iran",
  irak: "Iraq",
  iraq: "Iraq",
  irq: "Iraq",
  "ivory coast": "Ivory Coast",
  japon: "Japan",
  japan: "Japan",
  jordan: "Jordan",
  jordania: "Jordan",
  jor: "Jordan",
  jpn: "Japan",
  kor: "South Korea",
  ksa: "Saudi Arabia",
  mar: "Morocco",
  marruecos: "Morocco",
  mex: "Mexico",
  mexico: "Mexico",
  morocco: "Morocco",
  ned: "Netherlands",
  netherlands: "Netherlands",
  "new zealand": "New Zealand",
  nor: "Norway",
  noruega: "Norway",
  norway: "Norway",
  "nueva zelanda": "New Zealand",
  nzl: "New Zealand",
  "paises bajos": "Netherlands",
  pan: "Panama",
  panama: "Panama",
  par: "Paraguay",
  paraguay: "Paraguay",
  por: "Portugal",
  portugal: "Portugal",
  qat: "Qatar",
  qatar: "Qatar",
  "republica checa": "Czechia",
  "republica democratica del congo": "DR Congo",
  rsa: "South Africa",
  sco: "Scotland",
  scotland: "Scotland",
  sen: "Senegal",
  senegal: "Senegal",
  "south korea": "South Korea",
  "south africa": "South Africa",
  spain: "Spain",
  sudafrica: "South Africa",
  suecia: "Sweden",
  sui: "Switzerland",
  suiza: "Switzerland",
  swe: "Sweden",
  sweden: "Sweden",
  switzerland: "Switzerland",
  tun: "Tunisia",
  tunez: "Tunisia",
  tunisia: "Tunisia",
  tur: "Turkey",
  turkey: "Turkey",
  turquia: "Turkey",
  "united states": "United States",
  uru: "Uruguay",
  uruguay: "Uruguay",
  usa: "USA",
  uzbekistan: "Uzbekistan",
  uzb: "Uzbekistan",
};

export function flagForTeam(team: string) {
  const exactFlag = teamFlags[team];
  if (exactFlag) return exactFlag;

  const alias = teamFlagAliases[normalizeTeamName(team)];
  return alias ? teamFlags[alias] : "🏳️";
}
